Correction
ancka019/Homeworkss pull request #19
Opened 2020-08-22 16:47 UTC by ancka019

2020-08-24 07:18 UTC, yurii-litvinov requested changes

2020-08-24 07:18 UTC, yurii-litvinov commented on AnalogClock.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Проект попал прямо в корень репозитория, что, наверное, не то, что хотелось. Наведите порядок в гите, пожалуйста. Опять-таки, используя гитовый клиент на своём компе, не интерфейс гитхаба.

2020-08-24 07:18 UTC, yurii-litvinov commented on AnalogClock.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "AnalogClock", "AnalogClock\AnalogClock.csproj", "{55B5217C-2366-4865-83C5-F8720A20223B}"
AnalogClock.csproj лежит прямо тут же, а не в папке AnalogClock, .sln-ка не открывается. Всё потому, что надо выкладывать именно тот код, который Вы пишете, из папки, где Вы ведёте разработку, не копировать никуда ничего :)

2020-10-01 15:52 UTC, yurii-litvinov requested changes
.DS_Store не надо выкладывать, это файл, который имеет смысл только у Вас на компе. И содержимое папок bin и obj нельзя выкладывать, там бинарные файлы, которые можно без проблем получить, собрав исходники. Надо всё-таки прочитать хотя бы первые три главы git book (https://git-scm.com/book/ru/v2), ну и главу 5 заодно. 

Если Вы не освоите git, Вам нельзя ставить зачёт за второй семестр, это азы типа таблицы умножения :) Вообще, не стесняйтесь писать и спрашивать, можно даже созвониться по MS Teams и я всё покажу.

2020-10-01 15:52 UTC, yurii-litvinov commented on Clock.sln
> +Microsoft Visual Studio Solution File, Format Version 12.00
Теперь у Вас два Clock.sln

2020-10-01 15:52 UTC, yurii-litvinov commented on Clock/Clock/Clock.cs
> +﻿using System;
И Clock.cs теперь два

2020-10-01 16:10 UTC, yurii-litvinov commented on Clock/Clock/Clock.cs
> +﻿using System;
Если Вы добавляете что-то в коммит для того, чтобы что-то удалить, Вы уже делаете что-то не так :) Удалять файлы --- это команда git rm или её эквивалент в графическом клиенте

2020-10-01 16:12 UTC, Pugacheva019 commented
Я еще раз клонировала репозиторий и  повторила последний commit. У меня сейчас в репозитории на компьютере показывает, что остались только нужные файлы.

2020-10-01 16:21 UTC, Pugacheva019 commented on Clock/Clock/Clock.cs
> +﻿using System;
Да, я естественно использовала git rm. Но я просто имела ввиду , что если мы делаем какие-либо изменения, даже удаления файлов, то лучше это закоммит, чтобы легче было ориентироваться...(

2020-10-11 11:39 UTC, merged